import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { CamKart } from "@/bilesenler/akrep-ui";
import { HizliErisimDuzenleyici } from "@/bilesenler/hizli-erisim-duzenleyici";
import { useTarayici } from "@/lib/tarayici/baglam";

const temalar = [{ id: "orman", ad: "Orman", renk: "#1A6B12" }, { id: "grafit", ad: "Grafit", renk: "#35404E" }, { id: "kizil", ad: "Kızıl", renk: "#B84A29" }] as const;
export default function BaslangicAyarlariEkrani() {
  const { durum, ayariDegistir, hizliErisimEkle, hizliErisimGuncelle, hizliErisimSil, hizliErisimleriSirala } = useTarayici();
  const [duzenleyiciAcik, duzenleyiciAcikAyarla] = useState(false);
  const seciliTema = temalar.find((tema) => tema.id === durum.ayarlar.baslangicTemasi) || temalar[0];
  return <View style={styles.ekran}><ScrollView contentContainerStyle={styles.icerik}><View style={styles.ust}><Pressable accessibilityLabel="Geri dön" onPress={() => router.back()} style={styles.geri}><MaterialCommunityIcons name="arrow-left" size={22} color="#F6F8FB" /></Pressable><View style={styles.baslikMetin}><Text style={styles.baslik}>Başlangıç ekranı</Text><Text style={styles.altBaslik}>Açılış deneyimini kendine göre düzenle.</Text></View><MaterialCommunityIcons name="home-variant-outline" size={24} color="#FFB000" /></View><CamKart style={styles.onizlemeKart}><View style={[styles.onizleme, { backgroundColor: seciliTema.renk }]}><MaterialCommunityIcons name="zodiac-scorpio" size={33} color="#FFFFFF" /><Text style={styles.onizlemeAkrep}>Akrep</Text><View style={styles.onizlemeCubuk} /></View><Text style={styles.onizlemeAciklama}>Seçim ana sayfanın arka plan tonuna uygulanır.</Text></CamKart><Text style={styles.bolum}>Arka plan tonu</Text><View style={styles.temaSatiri}>{temalar.map((tema) => <Pressable key={tema.id} accessibilityRole="radio" accessibilityState={{ checked: durum.ayarlar.baslangicTemasi === tema.id }} onPress={() => ayariDegistir("baslangicTemasi", tema.id)} style={[styles.tema, durum.ayarlar.baslangicTemasi === tema.id && styles.temaEtkin]}><View style={[styles.temaNokta, { backgroundColor: tema.renk }]}>{durum.ayarlar.baslangicTemasi === tema.id ? <MaterialCommunityIcons name="check" size={16} color="#FFFFFF" /> : null}</View><Text style={styles.temaMetni}>{tema.ad}</Text></Pressable>)}</View><Text style={styles.bolum}>Hızlı erişim</Text><CamKart style={styles.hizliKart}><View style={styles.hizliSatir}><View style={styles.hizliSol}><MaterialCommunityIcons name="view-grid-plus-outline" size={22} color="#FF9F70" /><View><Text style={styles.hizliBaslik}>{durum.ayarlar.hizliErisimler.length} kısayol</Text><Text style={styles.hizliAciklama}>Ekle, düzenle, sil veya sırala.</Text></View></View><Pressable accessibilityLabel="Hızlı erişimleri düzenle" onPress={() => duzenleyiciAcikAyarla(true)} style={styles.duzenle}><Text style={styles.duzenleMetni}>Düzenle</Text></Pressable></View></CamKart></ScrollView><HizliErisimDuzenleyici acik={duzenleyiciAcik} ogeler={durum.ayarlar.hizliErisimler} onKapat={() => duzenleyiciAcikAyarla(false)} onEkle={hizliErisimEkle} onGuncelle={hizliErisimGuncelle} onSil={hizliErisimSil} onSirala={hizliErisimleriSirala} /></View>;
}
const styles = StyleSheet.create({ ekran: { flex: 1, backgroundColor: "#080B10" }, icerik: { padding: 18, paddingBottom: 36 }, ust: { flexDirection: "row", alignItems: "center", gap: 11 }, geri: { width: 39, height: 39, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#121821" }, baslikMetin: { flex: 1 }, baslik: { color: "#F6F8FB", fontSize: 21, fontWeight: "900" }, altBaslik: { color: "#8D9AAC", fontSize: 10, marginTop: 3 }, onizlemeKart: { padding: 13, marginTop: 18 }, onizleme: { height: 132, borderRadius: 17, alignItems: "center", justifyContent: "center" }, onizlemeAkrep: { color: "#FFFFFF", fontSize: 25, fontWeight: "500", marginTop: 2 }, onizlemeCubuk: { width: "76%", height: 28, borderRadius: 15, backgroundColor: "rgba(255,255,255,0.92)", marginTop: 11 }, onizlemeAciklama: { color: "#8491A0", fontSize: 9, marginTop: 10 }, bolum: { color: "#F6F8FB", fontSize: 13, fontWeight: "900", marginTop: 24, marginBottom: 8 }, temaSatiri: { flexDirection: "row", gap: 9 }, tema: { flex: 1, minHeight: 73, padding: 9, alignItems: "center", gap: 7, borderRadius: 17, backgroundColor: "#121821", borderWidth: 1, borderColor: "rgba(168,179,194,0.13)" }, temaEtkin: { borderColor: "#FFB000", backgroundColor: "#1B222C" }, temaNokta: { width: 31, height: 31, borderRadius: 16, alignItems: "center", justifyContent: "center" }, temaMetni: { color: "#D9E1E8", fontSize: 10, fontWeight: "800" }, hizliKart: { padding: 14 }, hizliSatir: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 }, hizliSol: { flex: 1, flexDirection: "row", alignItems: "center", gap: 10 }, hizliBaslik: { color: "#E9EDF2", fontSize: 12, fontWeight: "900" }, hizliAciklama: { color: "#8491A0", fontSize: 9, marginTop: 3 }, duzenle: { height: 34, paddingHorizontal: 11, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,176,0,0.14)" }, duzenleMetni: { color: "#FFCE63", fontSize: 10, fontWeight: "900" } });
