import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { CamKart } from "@/bilesenler/akrep-ui";
import { useTarayici } from "@/lib/tarayici/baglam";
import { SayfaNotu, SayfaVurgusu, urlBasligi } from "@/lib/tarayici/modeller";

type Satir = ({ tur: "not" } & SayfaNotu) | ({ tur: "vurgu" } & SayfaVurgusu);
export default function SayfaNotuEkrani() {
  const { etkinSekme, durum, notEkle, notuGuncelle, notSil, vurguSil } = useTarayici(); const [yeniNot, yeniNotAyarla] = useState("");
  const satirlar = useMemo<Satir[]>(() => [...durum.sayfaNotlari.filter((not) => not.url === etkinSekme.url).map((not) => ({ ...not, tur: "not" as const })), ...durum.sayfaVurgulari.filter((vurgu) => vurgu.url === etkinSekme.url).map((vurgu) => ({ ...vurgu, tur: "vurgu" as const }))].sort((a, b) => b.olusturulma - a.olusturulma), [durum.sayfaNotlari, durum.sayfaVurgulari, etkinSekme.url]);
  const ekle = () => { notEkle(etkinSekme.url, yeniNot); yeniNotAyarla(""); };
  return <View style={styles.ekran}><FlatList data={satirlar} keyExtractor={(item) => `${item.tur}-${item.id}`} contentContainerStyle={styles.icerik} ListHeaderComponent={<><View style={styles.ust}><Pressable accessibilityLabel="Geri dön" onPress={() => router.back()} style={styles.geri}><MaterialCommunityIcons name="arrow-left" size={22} color="#F6F8FB" /></Pressable><View style={styles.baslikMetin}><Text style={styles.baslik}>Sayfa notları</Text><Text numberOfLines={1} style={styles.url}>{urlBasligi(etkinSekme.url)}</Text></View><MaterialCommunityIcons name="notebook-edit-outline" size={25} color="#FFB000" /></View><CamKart style={styles.ekleKart}><Text style={styles.ekleBaslik}>Bu sayfaya not ekle</Text><TextInput accessibilityLabel="Yeni sayfa notu" multiline maxLength={1600} onChangeText={yeniNotAyarla} placeholder="Kendin için kısa bir not bırak…" placeholderTextColor="#718072" style={styles.girdi} value={yeniNot} /><Pressable accessibilityLabel="Notu kaydet" onPress={ekle} disabled={!yeniNot.trim()} style={[styles.kaydet, !yeniNot.trim() && styles.kaydetPasif]}><MaterialCommunityIcons name="content-save-outline" color="#080B10" size={18} /><Text style={styles.kaydetMetni}>Notu kaydet</Text></Pressable></CamKart><Text style={styles.bolum}>Kaydedilenler</Text></>} renderItem={({ item }) => item.tur === "not" ? <CamKart style={styles.kart}><View style={styles.kartUst}><MaterialCommunityIcons name="note-text-outline" color="#FF9F70" size={19} /><Text style={styles.kartEtiket}>Not</Text><Pressable accessibilityLabel="Notu sil" onPress={() => notSil(item.id)} style={styles.sil}><MaterialCommunityIcons name="trash-can-outline" color="#FF9AA2" size={17} /></Pressable></View><TextInput accessibilityLabel="Sayfa notunu düzenle" defaultValue={item.metin} multiline onEndEditing={(olay) => notuGuncelle(item.id, olay.nativeEvent.text)} style={styles.notMetni} /></CamKart> : <CamKart style={styles.kart}><View style={styles.kartUst}><MaterialCommunityIcons name="format-color-highlight" color={item.renk} size={19} /><Text style={styles.kartEtiket}>Vurgu</Text><Pressable accessibilityLabel="Vurguyu sil" onPress={() => vurguSil(item.id)} style={styles.sil}><MaterialCommunityIcons name="close" color="#FF9AA2" size={18} /></Pressable></View><Text style={[styles.vurguMetni, { backgroundColor: item.renk }]}>{item.seciliMetin}</Text></CamKart>} ListEmptyComponent={<CamKart style={styles.bos}><MaterialCommunityIcons name="note-plus-outline" size={30} color="#778598" /><Text style={styles.bosBaslik}>Bu sayfada not yok</Text><Text style={styles.bosAciklama}>Üç nokta menüsünden seçili metni vurgulayabilir veya yukarıdan not ekleyebilirsin.</Text></CamKart>} /> </View>;
}
const styles = StyleSheet.create({ ekran: { flex: 1, backgroundColor: "#080B10" }, icerik: { padding: 18, paddingBottom: 34 }, ust: { flexDirection: "row", alignItems: "center", gap: 11 }, geri: { width: 39, height: 39, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#121821" }, baslikMetin: { flex: 1 }, baslik: { color: "#F6F8FB", fontSize: 21, fontWeight: "900" }, url: { color: "#8D9AAC", fontSize: 10, marginTop: 3 }, ekleKart: { padding: 14, marginTop: 18 }, ekleBaslik: { color: "#F6F8FB", fontSize: 13, fontWeight: "900" }, girdi: { minHeight: 90, marginTop: 10, padding: 11, borderWidth: 1, borderRadius: 13, borderColor: "rgba(246,248,251,0.15)", color: "#E9EDF2", fontSize: 12, textAlignVertical: "top", backgroundColor: "rgba(246,248,251,0.04)" }, kaydet: { height: 41, marginTop: 9, borderRadius: 13, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, backgroundColor: "#FFB000" }, kaydetPasif: { opacity: 0.42 }, kaydetMetni: { color: "#080B10", fontSize: 12, fontWeight: "900" }, bolum: { color: "#A8B3C2", fontSize: 11, fontWeight: "900", marginTop: 22, marginBottom: 2 }, kart: { padding: 13, marginTop: 9 }, kartUst: { flexDirection: "row", alignItems: "center", gap: 7 }, kartEtiket: { flex: 1, color: "#DDE5EC", fontSize: 11, fontWeight: "900" }, sil: { width: 31, height: 31, borderRadius: 10, alignItems: "center", justifyContent: "center" }, notMetni: { minHeight: 48, marginTop: 8, color: "#C8D1DA", fontSize: 13, lineHeight: 19, textAlignVertical: "top" }, vurguMetni: { alignSelf: "flex-start", marginTop: 9, paddingHorizontal: 5, paddingVertical: 3, borderRadius: 4, color: "#303227", fontSize: 13, lineHeight: 20 }, bos: { padding: 25, alignItems: "center", marginTop: 7 }, bosBaslik: { color: "#E4EAF0", fontSize: 15, fontWeight: "900", marginTop: 9 }, bosAciklama: { color: "#8D9AAC", textAlign: "center", fontSize: 11, lineHeight: 17, marginTop: 5 } });
