import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router } from "expo-router";
import { useMemo } from "react";
import { FlatList, Pressable, StyleSheet, Switch, Text, View } from "react-native";

import { CamKart } from "@/bilesenler/akrep-ui";
import { useTarayici } from "@/lib/tarayici/baglam";
import { alanAdiCikar, SiteIzni } from "@/lib/tarayici/modeller";

const izinAlanlari: { anahtar: keyof Pick<SiteIzni, "kamera" | "mikrofon" | "konum" | "bildirim">; ad: string; icon: React.ComponentProps<typeof MaterialCommunityIcons>["name"] }[] = [{ anahtar: "kamera", ad: "Kamera", icon: "camera-outline" }, { anahtar: "mikrofon", ad: "Mikrofon", icon: "microphone-outline" }, { anahtar: "konum", ad: "Konum", icon: "map-marker-outline" }, { anahtar: "bildirim", ad: "Bildirim", icon: "bell-outline" }];
export default function SiteIzinleriEkrani() {
  const { etkinSekme, durum, siteIzniAyarla } = useTarayici(); const etkinAlan = alanAdiCikar(etkinSekme.url);
  const alanlar = useMemo(() => [...new Set([...(etkinAlan ? [etkinAlan] : []), ...durum.siteIzinleri.map((izin) => izin.alan)])], [durum.siteIzinleri, etkinAlan]);
  return <View style={styles.ekran}><FlatList data={alanlar} keyExtractor={(item) => item} contentContainerStyle={styles.icerik} ListHeaderComponent={<><View style={styles.ust}><Pressable accessibilityLabel="Geri dön" onPress={() => router.back()} style={styles.geri}><MaterialCommunityIcons name="arrow-left" size={22} color="#F6F8FB" /></Pressable><View style={styles.baslikMetin}><Text style={styles.baslik}>Site izinleri</Text><Text style={styles.altBaslik}>Her alan adı için cihaz erişimini sen belirlersin.</Text></View><MaterialCommunityIcons name="shield-key-outline" size={24} color="#FFB000" /></View><CamKart style={styles.bilgi}><MaterialCommunityIcons name="information-outline" size={18} color="#8EB6FF" /><Text style={styles.bilgiMetni}>Kamera, mikrofon ve konum isteği yalnızca bu ekranda izin verdiğin alanlar için WebView’e aktarılır.</Text></CamKart></>} renderItem={({ item: alan }) => <IzinKarti alan={alan} izin={durum.siteIzinleri.find((oge) => oge.alan === alan)} onDegis={(anahtar, deger) => siteIzniAyarla(alan, { [anahtar]: deger })} />} ListEmptyComponent={<CamKart style={styles.bos}><Text style={styles.bosMetin}>Bir HTTPS sayfası açtığında alan adı izinleri burada görünür.</Text></CamKart>} /> </View>;
}
function IzinKarti({ alan, izin, onDegis }: { alan: string; izin?: SiteIzni; onDegis: (anahtar: keyof Pick<SiteIzni, "kamera" | "mikrofon" | "konum" | "bildirim">, deger: boolean) => void }) { return <CamKart style={styles.kart}><View style={styles.kartUst}><View style={styles.alanSimge}><MaterialCommunityIcons name="web" size={20} color="#FF9F70" /></View><View style={styles.alanMetin}><Text style={styles.alan}>{alan}</Text><Text style={styles.alanAlt}>Varsayılan: tüm izinler kapalı</Text></View></View>{izinAlanlari.map((oge) => <View key={oge.anahtar} style={styles.izinSatiri}><MaterialCommunityIcons name={oge.icon} color="#A8B3C2" size={19} /><Text style={styles.izinAd}>{oge.ad}</Text><Switch accessibilityLabel={`${alan} için ${oge.ad} izni`} value={Boolean(izin?.[oge.anahtar])} onValueChange={(deger) => onDegis(oge.anahtar, deger)} trackColor={{ false: "#34404D", true: "#B95A32" }} thumbColor={izin?.[oge.anahtar] ? "#FFB000" : "#D9E1E8"} /></View>)}</CamKart>; }
const styles = StyleSheet.create({ ekran: { flex: 1, backgroundColor: "#080B10" }, icerik: { padding: 18, paddingBottom: 34 }, ust: { flexDirection: "row", alignItems: "center", gap: 11 }, geri: { width: 39, height: 39, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#121821" }, baslikMetin: { flex: 1 }, baslik: { color: "#F6F8FB", fontSize: 21, fontWeight: "900" }, altBaslik: { color: "#8D9AAC", fontSize: 10, lineHeight: 15, marginTop: 3 }, bilgi: { padding: 13, flexDirection: "row", gap: 9, marginTop: 18, alignItems: "flex-start", backgroundColor: "rgba(91,157,255,0.09)" }, bilgiMetni: { flex: 1, color: "#B7CAE8", fontSize: 10, lineHeight: 15 }, kart: { padding: 13, marginTop: 10 }, kartUst: { flexDirection: "row", gap: 10, alignItems: "center", paddingBottom: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "rgba(168,179,194,0.15)" }, alanSimge: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,159,112,0.10)" }, alanMetin: { flex: 1 }, alan: { color: "#F6F8FB", fontSize: 13, fontWeight: "900" }, alanAlt: { color: "#8D9AAC", fontSize: 9, marginTop: 3 }, izinSatiri: { minHeight: 48, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "rgba(168,179,194,0.12)" }, izinAd: { flex: 1, color: "#C8D1DA", fontSize: 12, fontWeight: "700" }, bos: { padding: 20, marginTop: 9 }, bosMetin: { color: "#8D9AAC", textAlign: "center", fontSize: 11 } });
