import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router } from "expo-router";
import { StyleSheet, Text, View } from "react-native";

import { BolumBasligi, CamKart, DurumRozeti, YuvarlakButon } from "@/bilesenler/akrep-ui";

export default function VpnEkrani() {
  return <View style={styles.ekran}><View style={styles.icerik}><BolumBasligi baslik="VPN kapsamı" aciklama="Bu sürümün gerçek ağ sınırı" /><CamKart style={styles.durumKart}><View style={styles.durumSimge}><MaterialCommunityIcons name="vpn" size={30} color="#FFB000" /></View><View style={styles.durumMetinleri}><Text style={styles.durumBaslik}>Cihaz genelinde VPN yok</Text><Text style={styles.durumAciklama}>Seçtiğin VPN’siz kapsam nedeniyle Android VpnService, WireGuard tüneli veya dış gateway başlatılmaz. Uygulama bağlıymış gibi görünmez.</Text></View><DurumRozeti metin="Kapalı" ton="uyari" /></CamKart><CamKart style={styles.bilgiKart}><MaterialCommunityIcons name="shield-check-outline" size={25} color="#68DC9A" /><View style={styles.bilgiMetinleri}><Text style={styles.bilgiBaslik}>Tarayıcı içi koruma etkin</Text><Text style={styles.bilgiAciklama}>HTTPS zorunluluğu ile WebView içindeki reklam ve takip koruması Akrep Tarayıcı’nın kendi oturumunda çalışır. Bu koruma, VPN veya cihaz çapında ağ gizleme değildir.</Text></View></CamKart><Text style={styles.altNot}>İleride gerçek VPN istenirse Android yerel VpnService, güvenli anahtar depolama ve sürekli çalışan WireGuard gateway birlikte kurulmalıdır.</Text><YuvarlakButon icon="arrow-left" etiket="Ana sayfaya dön" onPress={() => router.replace("/(tabs)" as never)} style={styles.altButon} /></View></View>;
}

const styles = StyleSheet.create({ ekran: { flex: 1, backgroundColor: "#080B10" }, icerik: { paddingHorizontal: 18, paddingBottom: 30 }, durumKart: { padding: 17, flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 10 }, durumSimge: { width: 55, height: 55, borderRadius: 19, justifyContent: "center", alignItems: "center", backgroundColor: "rgba(255,176,0,0.12)" }, durumMetinleri: { flex: 1 }, durumBaslik: { color: "#F6F8FB", fontSize: 16, lineHeight: 21, fontWeight: "900" }, durumAciklama: { color: "#A8B3C2", fontSize: 11, lineHeight: 16, marginTop: 3 }, bilgiKart: { padding: 17, flexDirection: "row", gap: 12, alignItems: "flex-start" }, bilgiMetinleri: { flex: 1 }, bilgiBaslik: { color: "#F6F8FB", fontSize: 14, fontWeight: "800" }, bilgiAciklama: { color: "#A8B3C2", fontSize: 11, lineHeight: 17, marginTop: 4 }, altNot: { color: "#7C899A", fontSize: 11, lineHeight: 16, textAlign: "center", paddingHorizontal: 16, marginTop: 24 }, altButon: { marginTop: 15, alignSelf: "center" } });
