import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router } from "expo-router";
import { FlatList, StyleSheet, Text, View } from "react-native";
import { BolumBasligi, CamKart, DurumRozeti, SimgeliSatir, YuvarlakButon } from "@/bilesenler/akrep-ui";

const gerekenler = [{ id: "motor", icon: "cellphone-cog" as const, baslik: "Android yerel VPN modülü", aciklama: "Gerçek VpnService ve WireGuard entegrasyonu Expo katmanının altında yerel Kotlin modülü gerektirir." }, { id: "gateway", icon: "server-network" as const, baslik: "WireGuard gateway", aciklama: "Doğrulanmış endpoint, public key, NAT, DNS ve IP forwarding içeren gerçek sunucu gereklidir." }, { id: "kontrol", icon: "shield-key-outline" as const, baslik: "Güvenli yapılandırma", aciklama: "İstemci private key'i güvenli depoda tutulur; kaynak koda veya arayüze yazılmaz." }, { id: "test", icon: "test-tube" as const, baslik: "Handshake ve leak testleri", aciklama: "Public IP, DNS, IPv6 ve ağ değişimi test edilmeden bağlı durumu yayınlanmaz." }];

export default function VpnEkrani() {
  return <View style={styles.ekran}><FlatList contentContainerStyle={styles.icerik} data={gerekenler} keyExtractor={(item) => item.id} ListHeaderComponent={<><BolumBasligi baslik="VPN merkezi" aciklama="Gerçek bağlantı için gereken bileşenler" /><CamKart style={styles.durumKart}><View style={styles.durumSimge}><MaterialCommunityIcons name="vpn" size={30} color="#FFB000" /></View><View style={styles.durumMetinleri}><Text style={styles.durumBaslik}>Bağlantı kurulmadı</Text><Text style={styles.durumAciklama}>Sunucu, WireGuard profili ve Android yerel VPN motoru yapılandırılmadığı için uygulama bağlı görünmez.</Text></View><DurumRozeti metin="Kurulum gerekli" ton="uyari" /></CamKart></>} renderItem={({ item }) => <CamKart style={styles.kart}><SimgeliSatir icon={item.icon} iconRengi="#FFB000" baslik={item.baslik} aciklama={item.aciklama} /></CamKart>} ListFooterComponent={<View style={styles.altAlan}><Text style={styles.altNot}>VPN düğmesi yalnızca gerçek Android VpnService → WireGuard → gateway zinciri hazır olduğunda bağlantı başlatacaktır.</Text><YuvarlakButon icon="arrow-left" etiket="Ana sayfaya dön" onPress={() => router.replace("/(tabs)")} style={styles.altButon} /></View>} /></View>;
}

const styles = StyleSheet.create({ ekran: { flex: 1, backgroundColor: "#080B10" }, icerik: { paddingHorizontal: 18, paddingBottom: 30 }, durumKart: { padding: 17, flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 8 }, durumSimge: { width: 55, height: 55, borderRadius: 19, justifyContent: "center", alignItems: "center", backgroundColor: "rgba(255, 176, 0, 0.12)" }, durumMetinleri: { flex: 1 }, durumBaslik: { color: "#F6F8FB", fontSize: 16, lineHeight: 21, fontWeight: "900" }, durumAciklama: { color: "#A8B3C2", fontSize: 11, lineHeight: 16, marginTop: 3 }, kart: { marginTop: 10, paddingHorizontal: 14 }, altAlan: { alignItems: "center", marginTop: 24 }, altNot: { color: "#7C899A", fontSize: 11, lineHeight: 16, textAlign: "center", paddingHorizontal: 16 }, altButon: { marginTop: 15 } });
