import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router } from "expo-router";
import { FlatList, StyleSheet, Text, View } from "react-native";
import { BolumBasligi, CamKart, DurumRozeti, SimgeliSatir, YuvarlakButon } from "@/bilesenler/akrep-ui";

const araclar = [{ id: "ozet", icon: "text-short" as const, baslik: "Sayfayı özetle", aciklama: "Kullanıcı onayıyla yalnızca seçilen sayfa metnini işler." }, { id: "ceviri", icon: "translate" as const, baslik: "Türkçeye çevir", aciklama: "Orijinal metne dönme ve kaynak bağlantısını koruma kuralıyla tasarlanır." }, { id: "soru", icon: "comment-question-outline" as const, baslik: "Sayfaya soru sor", aciklama: "Cevabı kaynak bağlamı ile ilişkilendirir; sayfada olmayan bilgiyi uydurmaz." }, { id: "gorsel", icon: "image-search-outline" as const, baslik: "Görseli açıkla", aciklama: "Görsel gönderilmeden önce veri paylaşımı ve hassas içerik uyarısı gösterir." }];

export default function YapayZekaEkrani() { return <View style={styles.ekran}><FlatList contentContainerStyle={styles.icerik} data={araclar} keyExtractor={(item) => item.id} ListHeaderComponent={<><BolumBasligi baslik="Yapay zekâ merkezi" aciklama="İzinli sayfa analizi için hazırlık" /><CamKart style={styles.durumKart}><View style={styles.durumSimge}><MaterialCommunityIcons name="creation" color="#FF6A2A" size={29} /></View><View style={styles.durumMetinleri}><Text style={styles.durumBaslik}>Sağlayıcı bağlantısı bekleniyor</Text><Text style={styles.durumAciklama}>Üretken yanıt, özet veya çeviri; sunucu tarafı işlem ve kullanıcı onayı olmadan gösterilmez.</Text></View><DurumRozeti metin="Hazırlık" ton="uyari" /></CamKart></>} renderItem={({ item }) => <CamKart style={styles.kart}><SimgeliSatir icon={item.icon} iconRengi="#FF6A2A" baslik={item.baslik} aciklama={item.aciklama} /></CamKart>} ListFooterComponent={<View style={styles.altAlan}><Text style={styles.altNot}>İleride etkinleştirildiğinde, araçlar sayfa verisi gönderilmeden önce açık izin ister ve kaynakla desteklenemeyen cevabı kesin gerçek gibi sunmaz.</Text><YuvarlakButon icon="arrow-left" etiket="Ana sayfaya dön" onPress={() => router.replace("/(tabs)" as never)} style={styles.altButon} /></View>} /></View>; }
const styles = StyleSheet.create({ ekran: { flex: 1, backgroundColor: "#080B10" }, icerik: { paddingHorizontal: 18, paddingBottom: 30 }, durumKart: { padding: 17, flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 8 }, durumSimge: { width: 55, height: 55, borderRadius: 19, justifyContent: "center", alignItems: "center", backgroundColor: "rgba(255, 106, 42, 0.13)" }, durumMetinleri: { flex: 1 }, durumBaslik: { color: "#F6F8FB", fontSize: 16, lineHeight: 21, fontWeight: "900" }, durumAciklama: { color: "#A8B3C2", fontSize: 11, lineHeight: 16, marginTop: 3 }, kart: { marginTop: 10, paddingHorizontal: 14 }, altAlan: { alignItems: "center", marginTop: 24 }, altNot: { color: "#7C899A", fontSize: 11, lineHeight: 16, textAlign: "center", paddingHorizontal: 16 }, altButon: { marginTop: 15 } });
