import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";

import { CamKart, YuvarlakButon } from "@/bilesenler/akrep-ui";
import { useTarayici } from "@/lib/tarayici/baglam";

export default function YetiskinUyumEkrani() {
  const { durum } = useTarayici();
  return <View style={styles.ekran}><ScrollView contentContainerStyle={styles.icerik}><View style={styles.baslikSatiri}><MaterialCommunityIcons name="shield-account-outline" color="#FFB000" size={25} /><View><Text style={styles.baslik}>Yetişkin erişim ve uyum</Text><Text style={styles.altBaslik}>Yerel erişim durumu ve yayın notları</Text></View></View><CamKart style={styles.durumKart}><Text style={styles.durumBaslik}>Yerel yaş onayı: {durum.ayarlar.yetiskinErisimOnayi ? "Onaylı" : "Onaysız"}</Text><Text style={styles.durumMetni}>Bu durum, cihazdaki erişim kapısında verilen beyana dayanır. Kimlik veya yaş tahmini doğrulaması değildir.</Text></CamKart><BaslikliKart icon="account-check-outline" baslik="Yalnızca yetişkin erişimi" metin="Reşit olmayanların erişimi yasaktır. Rıza dışı, sömürücü veya hukuka aykırı içerik hiçbir koşulda kabul edilmez." /><BaslikliKart icon="magnify" baslik="Kullanıcı başlatmalı arama" metin="Arama motoru tercihi Google veya Yandex olarak kullanıcı tarafından seçilir. Akrep içerik sağlamaz, önermez veya barındırmaz." /><BaslikliKart icon="scale-balance" baslik="Yayın ve ülke uyumu" metin="Hedef ülkeye göre yaş doğrulama, veri koruması, içerik sınıflandırması ve dağıtım kuralları değişir. Yayın öncesinde yerel uzman incelemesi ve gerekiyorsa harici güçlü yaş güvence sağlayıcısı gerekir." /><BaslikliKart icon="store-off-outline" baslik="Mağaza kısıtı" metin="Google Play ve Apple App Store politikaları pornografik uygulamaları genel olarak kabul etmez. Yetişkin odaklı ürün için dağıtım modelini ve mağaza politikalarını ayrı değerlendirmek gerekir." /><YuvarlakButon icon="arrow-left" etiket="Ana sayfaya dön" onPress={() => router.replace("/(tabs)" as never)} style={styles.altButon} /></ScrollView></View>;
}

function BaslikliKart({ icon, baslik, metin }: { icon: React.ComponentProps<typeof MaterialCommunityIcons>["name"]; baslik: string; metin: string }) { return <CamKart style={styles.kart}><MaterialCommunityIcons name={icon} color="#FFB000" size={22} /><View style={styles.kartMetinleri}><Text style={styles.kartBaslik}>{baslik}</Text><Text style={styles.kartMetni}>{metin}</Text></View></CamKart>; }

const styles = StyleSheet.create({ ekran: { flex: 1, backgroundColor: "#080B10" }, icerik: { padding: 20, paddingBottom: 34 }, baslikSatiri: { flexDirection: "row", gap: 11, alignItems: "center", marginTop: 8, marginBottom: 18 }, baslik: { color: "#F6F8FB", fontSize: 20, fontWeight: "900" }, altBaslik: { color: "#A8B3C2", fontSize: 11, marginTop: 3 }, durumKart: { padding: 16, marginBottom: 10, borderColor: "rgba(131,219,165,0.28)" }, durumBaslik: { color: "#83DBA5", fontSize: 14, fontWeight: "800" }, durumMetni: { color: "#B4C0CE", fontSize: 11, lineHeight: 16, marginTop: 5 }, kart: { padding: 15, marginTop: 10, flexDirection: "row", gap: 12, alignItems: "flex-start" }, kartMetinleri: { flex: 1 }, kartBaslik: { color: "#F6F8FB", fontSize: 14, fontWeight: "800" }, kartMetni: { color: "#A8B3C2", fontSize: 11, lineHeight: 17, marginTop: 4 }, altButon: { alignSelf: "center", marginTop: 23 } });
