import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { router as expoRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { BolumBasligi, CamKart, DurumRozeti, YuvarlakButon } from "@/bilesenler/akrep-ui";
import { useTarayici } from "@/lib/tarayici/baglam";
import { Sekme, SekmeTuru, YENI_SEKME_URL } from "@/lib/tarayici/modeller";

const router = {
  push: (rota: string) => expoRouter.push(rota as never),
};

export default function SekmelerEkrani() {
  const { durum, etkinSekme, etkinSekmeyiDegistir, sekmeAc, sekmeKapat } = useTarayici();
  const [filtre, filtreAyarla] = useState<SekmeTuru>("normal");
  const gorunenSekmeler = useMemo(() => durum.sekmeler.filter((sekme) => sekme.tur === filtre), [durum.sekmeler, filtre]);
  const sekmeAcVeTarayiciyaGit = (tur: SekmeTuru) => { sekmeAc(undefined, tur); router.push("/tarayici"); };
  return <View style={styles.ekran}><FlatList contentContainerStyle={styles.icerik} data={gorunenSekmeler} keyExtractor={(item) => item.id} ListHeaderComponent={<><BolumBasligi baslik="Sekme merkezi" aciklama="Açık sayfaların gerçek listesi" /><View style={styles.filtreler}><Pressable onPress={() => filtreAyarla("normal")} style={[styles.filtre, filtre === "normal" && styles.filtreEtkin]}><MaterialCommunityIcons name="tab" size={16} color={filtre === "normal" ? "#080B10" : "#A8B3C2"} /><Text style={[styles.filtreMetni, filtre === "normal" && styles.filtreMetniEtkin]}>Normal</Text></Pressable><Pressable onPress={() => filtreAyarla("gizli")} style={[styles.filtre, filtre === "gizli" && styles.filtreEtkin]}><MaterialCommunityIcons name="incognito" size={16} color={filtre === "gizli" ? "#080B10" : "#A8B3C2"} /><Text style={[styles.filtreMetni, filtre === "gizli" && styles.filtreMetniEtkin]}>Gizli</Text></Pressable></View><View style={styles.sayiSatiri}><DurumRozeti metin={`${gorunenSekmeler.length} açık sekme`} ton={filtre === "gizli" ? "uyari" : "nötr"} /><Text style={styles.sayiAciklamasi}>{filtre === "gizli" ? "Gizli sekmeler geçmişe yazılmaz." : "Sekmeye dokunarak açabilirsin."}</Text></View></>} ListEmptyComponent={<CamKart style={styles.bosKart}><MaterialCommunityIcons name={filtre === "gizli" ? "incognito" : "tab-plus"} size={28} color="#FFB000" /><Text style={styles.bosBaslik}>Bu grupta sekme yok</Text><Text style={styles.bosAciklama}>{filtre === "gizli" ? "Gizli sekmeler hiçbir normal geçmişe eklenmez." : "Yeni bir sayfa açarak taramaya başla."}</Text></CamKart>} renderItem={({ item }) => <SekmeKarti etkin={item.id === etkinSekme.id} sekme={item} onAc={() => { etkinSekmeyiDegistir(item.id); router.push("/tarayici"); }} onKapat={() => sekmeKapat(item.id)} />} ListFooterComponent={<View style={styles.altButonlar}><YuvarlakButon icon="plus" etiket="Yeni sekme" tur="birincil" onPress={() => sekmeAcVeTarayiciyaGit("normal")} style={styles.butunButon} /><YuvarlakButon icon="incognito" etiket="Gizli sekme" onPress={() => sekmeAcVeTarayiciyaGit("gizli")} style={styles.butunButon} /></View>} showsVerticalScrollIndicator={false} /></View>;
}

function SekmeKarti({ sekme, etkin, onAc, onKapat }: { sekme: Sekme; etkin: boolean; onAc: () => void; onKapat: () => void }) {
  const yeniSekmeMi = sekme.url === YENI_SEKME_URL;
  return <CamKart style={[styles.sekmeKart, etkin && styles.etkinSekmeKart]}><Pressable onPress={onAc} style={({ pressed }) => [styles.sekmeIcerik, pressed && styles.basili]}><View style={[styles.sekmeSimge, sekme.tur === "gizli" && styles.gizliSimge]}><MaterialCommunityIcons name={sekme.tur === "gizli" ? "incognito" : yeniSekmeMi ? "plus" : "web"} size={20} color={sekme.tur === "gizli" ? "#FFB000" : "#FF6A2A"} /></View><View style={styles.sekmeMetinleri}><Text numberOfLines={1} style={styles.sekmeBasligi}>{sekme.baslik}</Text><Text numberOfLines={1} style={styles.sekmeUrl}>{yeniSekmeMi ? "Akrep başlangıç ekranı" : sekme.url}</Text></View>{etkin ? <DurumRozeti metin="Açık" ton="basari" /> : null}</Pressable><Pressable accessibilityLabel="Sekmeyi kapat" onPress={onKapat} style={({ pressed }) => [styles.kapatButonu, pressed && styles.basili]}><MaterialCommunityIcons name="close" size={18} color="#A8B3C2" /></Pressable></CamKart>;
}

const styles = StyleSheet.create({ ekran: { flex: 1, backgroundColor: "#080B10" }, icerik: { paddingHorizontal: 18, paddingBottom: 28 }, filtreler: { flexDirection: "row", gap: 9 }, filtre: { flex: 1, minHeight: 44, borderRadius: 18, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: "#121821", borderWidth: 1, borderColor: "rgba(168, 179, 194, 0.13)" }, filtreEtkin: { backgroundColor: "#FFB000", borderColor: "#FFD269" }, filtreMetni: { color: "#A8B3C2", fontSize: 13, fontWeight: "800" }, filtreMetniEtkin: { color: "#080B10" }, sayiSatiri: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 14, marginBottom: 9, gap: 10 }, sayiAciklamasi: { flex: 1, color: "#8D9AAC", fontSize: 11, lineHeight: 15, textAlign: "right" }, sekmeKart: { marginTop: 10, flexDirection: "row", alignItems: "center", padding: 7 }, etkinSekmeKart: { borderColor: "rgba(255, 106, 42, 0.5)", backgroundColor: "#18202B" }, sekmeIcerik: { flex: 1, flexDirection: "row", alignItems: "center", gap: 12, minHeight: 58 }, sekmeSimge: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255, 106, 42, 0.1)" }, gizliSimge: { backgroundColor: "rgba(255, 176, 0, 0.11)" }, sekmeMetinleri: { flex: 1 }, sekmeBasligi: { color: "#F6F8FB", fontSize: 14, lineHeight: 20, fontWeight: "800" }, sekmeUrl: { color: "#8D9AAC", fontSize: 11, lineHeight: 16, marginTop: 2 }, kapatButonu: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 16 }, bosKart: { padding: 26, alignItems: "center", gap: 6, marginTop: 10 }, bosBaslik: { color: "#F6F8FB", fontSize: 16, lineHeight: 21, fontWeight: "800", marginTop: 4 }, bosAciklama: { color: "#A8B3C2", fontSize: 12, lineHeight: 18, textAlign: "center" }, altButonlar: { flexDirection: "row", gap: 10, marginTop: 22 }, butunButon: { flex: 1 }, basili: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
