import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import DraggableFlatList, { RenderItemParams } from "react-native-draggable-flatlist";
import { router as expoRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";

import { BolumBasligi, CamKart, DurumRozeti, YuvarlakButon } from "@/bilesenler/akrep-ui";
import { SekmeGrubuDuzenleyici } from "@/bilesenler/sekme-grubu-duzenleyici";
import { useTarayici } from "@/lib/tarayici/baglam";
import { Sekme, SekmeGrubu, SekmeTuru, YENI_SEKME_URL } from "@/lib/tarayici/modeller";

const router = { push: (rota: string) => expoRouter.push(rota as never) };
export default function SekmelerEkrani() {
  const { durum, etkinSekme, etkinSekmeyiDegistir, sekmeAc, sekmeKapat, sekmeGrubuOlustur, sekmeGrubunuGuncelle, sekmeleriSirala, sekmeyiSabitle, sekmeyiUyut, kapatilanSekmeyiGeriAc } = useTarayici();
  const [filtre, filtreAyarla] = useState<SekmeTuru>("normal"); const [grupFiltresi, grupFiltresiAyarla] = useState("tum"); const [duzenlenenGrup, duzenlenenGrupAyarla] = useState<SekmeGrubu | null>(null);
  const gorunen = useMemo(() => durum.sekmeler.filter((sekme) => sekme.tur === filtre && (grupFiltresi === "tum" || sekme.grupId === grupFiltresi)).sort((a, b) => Number(Boolean(b.sabitlenmis)) - Number(Boolean(a.sabitlenmis))), [durum.sekmeler, filtre, grupFiltresi]);
  const paylas = async () => { const sekmeler = durum.sekmeler.filter((sekme) => sekme.tur === "normal" && sekme.url !== YENI_SEKME_URL); if (!sekmeler.length) return; await Share.share({ title: "Akrep açık sekmeleri", message: `Akrep Tarayıcı açık sekmeleri\n\n${sekmeler.map((sekme, indeks) => `${indeks + 1}. ${sekme.baslik}\n${sekme.url}`).join("\n\n")}` }); };
  const baslik = <><BolumBasligi baslik="Sekme merkezi" aciklama="Uzun basılı tutup sekmeleri sürükleyerek sırala" /><View style={styles.ustEylem}><Pressable accessibilityLabel="Açık sekmeleri paylaş" onPress={() => void paylas()} style={styles.paylas}><MaterialCommunityIcons name="share-variant-outline" size={18} color="#FFCE63" /><Text style={styles.paylasMetni}>Listeyi paylaş</Text></Pressable><Pressable accessibilityLabel="Yeni sekme grubu oluştur" onPress={() => sekmeGrubuOlustur(`Grup ${durum.sekmeGruplari.length + 1}`)} style={styles.paylas}><MaterialCommunityIcons name="folder-plus-outline" size={18} color="#FFCE63" /><Text style={styles.paylasMetni}>Grup</Text></Pressable></View><View style={styles.filtreler}><Filtre etkin={filtre === "normal"} ad="Normal" icon="tab" onPress={() => { filtreAyarla("normal"); grupFiltresiAyarla("tum"); }} /><Filtre etkin={filtre === "gizli"} ad="Gizli" icon="incognito" onPress={() => { filtreAyarla("gizli"); grupFiltresiAyarla("tum"); }} /></View>{filtre === "normal" ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.grupSatiri}><GrupCipi etkin={grupFiltresi === "tum"} etiket="Tümü" onPress={() => grupFiltresiAyarla("tum")} />{durum.sekmeGruplari.map((grup) => <GrupCipi key={grup.id} etkin={grupFiltresi === grup.id} etiket={grup.ad} renk={grup.renk} onPress={() => grupFiltresiAyarla(grup.id)} onDuzenle={() => duzenlenenGrupAyarla(grup)} />)}</ScrollView> : null}{durum.kapatilanSekmeler.length && filtre === "normal" ? <CamKart style={styles.kapatilanKart}><Text style={styles.kapatilanBaslik}>Son kapatılan sekmeler</Text>{durum.kapatilanSekmeler.slice(0, 2).map((kayit) => <Pressable key={kayit.id} onPress={() => { kapatilanSekmeyiGeriAc(kayit.id); router.push("/tarayici"); }} style={styles.kapatilanSatir}><MaterialCommunityIcons name="restore" color="#FFB000" size={17} /><Text numberOfLines={1} style={styles.kapatilanMetin}>{kayit.sekme.baslik}</Text><Text style={styles.geriAc}>Geri aç</Text></Pressable>)}</CamKart> : null}<View style={styles.sayiSatiri}><DurumRozeti metin={`${gorunen.length} açık sekme`} ton={filtre === "gizli" ? "uyari" : "nötr"} /><Text style={styles.sayiMetni}>{filtre === "normal" ? "Sürükle-bırak sıralama açık" : "Gizli sekmeler geçmişe yazılmaz"}</Text></View></>;
  return <View style={styles.ekran}><DraggableFlatList data={gorunen} keyExtractor={(item) => item.id} ListHeaderComponent={baslik} ListEmptyComponent={<CamKart style={styles.bos}><MaterialCommunityIcons name="tab-plus" color="#778598" size={29} /><Text style={styles.bosBaslik}>Bu alanda sekme yok</Text></CamKart>} contentContainerStyle={styles.icerik} renderItem={(params) => <SekmeKarti {...params} etkin={params.item.id === etkinSekme.id} grupAdi={durum.sekmeGruplari.find((grup) => grup.id === params.item.grupId)?.ad} onAc={() => { etkinSekmeyiDegistir(params.item.id); router.push("/tarayici"); }} onKapat={() => sekmeKapat(params.item.id)} onSabitle={() => sekmeyiSabitle(params.item.id)} onUyut={() => sekmeyiUyut(params.item.id)} />} onDragEnd={({ data }) => sekmeleriSirala(data.map((sekme) => sekme.id))} ListFooterComponent={<View style={styles.alt}><YuvarlakButon icon="plus" etiket="Yeni sekme" tur="birincil" onPress={() => { sekmeAc(); router.push("/tarayici"); }} style={styles.altButon} /><YuvarlakButon icon="incognito" etiket="Gizli sekme" onPress={() => { sekmeAc(undefined, "gizli"); router.push("/tarayici"); }} style={styles.altButon} /></View>} /><SekmeGrubuDuzenleyici grup={duzenlenenGrup} acik={Boolean(duzenlenenGrup)} onKapat={() => duzenlenenGrupAyarla(null)} onKaydet={(id, ad, renk) => sekmeGrubunuGuncelle(id, { ad, renk })} /></View>;
}
function Filtre({ etkin, ad, icon, onPress }: { etkin: boolean; ad: string; icon: React.ComponentProps<typeof MaterialCommunityIcons>["name"]; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.filtre, etkin && styles.filtreEtkin]}><MaterialCommunityIcons name={icon} size={16} color={etkin ? "#080B10" : "#A8B3C2"} /><Text style={[styles.filtreMetin, etkin && styles.filtreMetinEtkin]}>{ad}</Text></Pressable>; }
function GrupCipi({ etiket, etkin, renk = "#607C9B", onPress, onDuzenle }: { etiket: string; etkin: boolean; renk?: string; onPress: () => void; onDuzenle?: () => void }) { return <View style={[styles.grupCipi, etkin && { borderColor: renk, backgroundColor: `${renk}22` }]}><Pressable onPress={onPress} style={styles.grupAna}><View style={[styles.grupNokta, { backgroundColor: renk }]} /><Text style={styles.grupMetin}>{etiket}</Text></Pressable>{onDuzenle ? <Pressable accessibilityLabel={`${etiket} grubunu düzenle`} onPress={onDuzenle} style={styles.grupDuzenle}><MaterialCommunityIcons name="pencil-outline" size={12} color="#A8B3C2" /></Pressable> : null}</View>; }
function SekmeKarti({ item, drag, isActive, etkin, grupAdi, onAc, onKapat, onSabitle, onUyut }: RenderItemParams<Sekme> & { etkin: boolean; grupAdi?: string; onAc: () => void; onKapat: () => void; onSabitle: () => void; onUyut: () => void }) { const yeni = item.url === YENI_SEKME_URL; return <CamKart style={[styles.sekmeKart, etkin && styles.etkin, isActive && styles.surukleniyor]}><Pressable accessibilityLabel="Sekmeyi sürüklemek için basılı tut" onLongPress={drag} delayLongPress={180} style={styles.tutama}><MaterialCommunityIcons name="drag-vertical" size={21} color="#778598" /></Pressable><Pressable onPress={onAc} style={styles.sekmeIcerik}><View style={styles.sekmeSimge}><MaterialCommunityIcons name={item.tur === "gizli" ? "incognito" : yeni ? "plus" : item.uyuyor ? "sleep" : "web"} size={20} color={item.tur === "gizli" ? "#FFB000" : "#FF6A2A"} /></View><View style={styles.sekmeMetin}><Text numberOfLines={1} style={styles.sekmeBaslik}>{item.baslik}</Text><Text numberOfLines={1} style={styles.sekmeUrl}>{grupAdi ? `${grupAdi} · ` : ""}{item.uyuyor ? "Uyuyan sekme" : yeni ? "Akrep başlangıç" : item.url}</Text></View>{etkin ? <DurumRozeti metin="Açık" ton="basari" /> : null}</Pressable><View style={styles.kartEylem}><Pressable accessibilityLabel="Sekmeyi sabitle" onPress={onSabitle} style={styles.kucuk}><MaterialCommunityIcons name={item.sabitlenmis ? "pin" : "pin-outline"} size={16} color="#A8B3C2" /></Pressable><Pressable accessibilityLabel="Sekmeyi uyut" onPress={onUyut} style={styles.kucuk}><MaterialCommunityIcons name={item.uyuyor ? "weather-sunny" : "sleep"} size={16} color="#A8B3C2" /></Pressable><Pressable accessibilityLabel="Sekmeyi kapat" onPress={onKapat} style={styles.kucuk}><MaterialCommunityIcons name="close" size={18} color="#A8B3C2" /></Pressable></View></CamKart>; }
const styles = StyleSheet.create({ ekran: { flex: 1, backgroundColor: "#080B10" }, icerik: { paddingHorizontal: 18, paddingBottom: 30 }, ustEylem: { flexDirection: "row", gap: 8, marginBottom: 10 }, paylas: { flex: 1, height: 38, borderRadius: 13, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, backgroundColor: "rgba(255,176,0,0.10)", borderWidth: 1, borderColor: "rgba(255,176,0,0.23)" }, paylasMetni: { color: "#FFCE63", fontSize: 10, fontWeight: "900" }, filtreler: { flexDirection: "row", gap: 9 }, filtre: { flex: 1, height: 43, borderRadius: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, backgroundColor: "#121821" }, filtreEtkin: { backgroundColor: "#FFB000" }, filtreMetin: { color: "#A8B3C2", fontSize: 12, fontWeight: "900" }, filtreMetinEtkin: { color: "#080B10" }, grupSatiri: { gap: 7, paddingTop: 12, paddingBottom: 4 }, grupCipi: { minHeight: 32, paddingLeft: 10, paddingRight: 4, borderRadius: 12, borderWidth: 1, borderColor: "rgba(168,179,194,0.20)", flexDirection: "row", alignItems: "center", backgroundColor: "#121821" }, grupAna: { flexDirection: "row", alignItems: "center", gap: 6 }, grupNokta: { width: 7, height: 7, borderRadius: 4 }, grupMetin: { color: "#C8D1DA", fontSize: 10, fontWeight: "800" }, grupDuzenle: { width: 25, height: 27, alignItems: "center", justifyContent: "center", marginLeft: 3 }, kapatilanKart: { padding: 11, marginTop: 10 }, kapatilanBaslik: { color: "#E9EDF2", fontSize: 11, fontWeight: "900" }, kapatilanSatir: { minHeight: 31, marginTop: 5, flexDirection: "row", alignItems: "center", gap: 7 }, kapatilanMetin: { flex: 1, color: "#A8B3C2", fontSize: 10 }, geriAc: { color: "#FFB000", fontSize: 9, fontWeight: "900" }, sayiSatiri: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 12, marginBottom: 3 }, sayiMetni: { color: "#8290A1", fontSize: 9 }, sekmeKart: { padding: 7, marginTop: 9, flexDirection: "row", alignItems: "center" }, etkin: { borderColor: "rgba(255,106,42,0.5)", backgroundColor: "#18202B" }, surukleniyor: { opacity: 0.82, borderColor: "#FFB000" }, tutama: { width: 27, minHeight: 59, justifyContent: "center", alignItems: "center" }, sekmeIcerik: { flex: 1, minHeight: 58, flexDirection: "row", alignItems: "center", gap: 10 }, sekmeSimge: { width: 39, height: 39, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,106,42,0.1)" }, sekmeMetin: { flex: 1 }, sekmeBaslik: { color: "#F6F8FB", fontSize: 13, fontWeight: "800" }, sekmeUrl: { color: "#8D9AAC", fontSize: 9, marginTop: 3 }, kartEylem: { flexDirection: "row" }, kucuk: { width: 28, height: 42, justifyContent: "center", alignItems: "center" }, bos: { marginTop: 12, padding: 25, alignItems: "center" }, bosBaslik: { color: "#E9EDF2", fontSize: 14, fontWeight: "800", marginTop: 8 }, alt: { flexDirection: "row", gap: 10, marginTop: 20 }, altButon: { flex: 1 } });
