import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { useEffect, useState } from "react";
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import type { SekmeGrubu } from "@/lib/tarayici/modeller";

const renkler = ["#FF6A2A", "#7AA6FF", "#A981FF", "#27D17F", "#F7D65C", "#F35C87"];
export function SekmeGrubuDuzenleyici({ grup, acik, onKapat, onKaydet }: { grup: SekmeGrubu | null; acik: boolean; onKapat: () => void; onKaydet: (id: string, ad: string, renk: string) => void }) {
  const [ad, adAyarla] = useState(""); const [renk, renkAyarla] = useState(renkler[0]);
  useEffect(() => { if (grup) { adAyarla(grup.ad); renkAyarla(grup.renk); } }, [grup]);
  if (!grup) return null;
  return <Modal transparent animationType="fade" visible={acik} onRequestClose={onKapat}><Pressable onPress={onKapat} style={styles.perde}><Pressable onPress={(olay) => olay.stopPropagation()} style={styles.panel}><View style={styles.ust}><View><Text style={styles.baslik}>Sekme grubunu düzenle</Text><Text style={styles.aciklama}>Adı ve renk işaretini değiştirebilirsin.</Text></View><Pressable accessibilityLabel="Düzenleyiciyi kapat" onPress={onKapat} style={styles.kapat}><MaterialCommunityIcons name="close" color="#32372D" size={20} /></Pressable></View><TextInput accessibilityLabel="Sekme grubu adı" maxLength={28} onChangeText={adAyarla} placeholder="Grup adı" placeholderTextColor="#849080" style={styles.girdi} value={ad} /><View style={styles.renkler}>{renkler.map((oge) => <Pressable key={oge} accessibilityLabel="Grup rengi seç" onPress={() => renkAyarla(oge)} style={[styles.renk, { backgroundColor: oge }, renk === oge && styles.renkEtkin]}>{renk === oge ? <MaterialCommunityIcons name="check" color="#080B10" size={17} /> : null}</Pressable>)}</View><Pressable accessibilityLabel="Sekme grubunu kaydet" onPress={() => { onKaydet(grup.id, ad, renk); onKapat(); }} style={styles.kaydet}><Text style={styles.kaydetMetni}>Değişiklikleri kaydet</Text><MaterialCommunityIcons name="check" color="#080B10" size={18} /></Pressable></Pressable></Pressable></Modal>;
}
const styles = StyleSheet.create({ perde: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.45)", padding: 15 }, panel: { borderRadius: 25, padding: 18, backgroundColor: "#F7F9EA" }, ust: { flexDirection: "row", justifyContent: "space-between", gap: 12 }, baslik: { color: "#29322D", fontSize: 17, fontWeight: "900" }, aciklama: { color: "#667066", fontSize: 10, marginTop: 4 }, kapat: { width: 35, height: 35, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#E8EDDF" }, girdi: { height: 49, marginTop: 17, paddingHorizontal: 14, color: "#29322D", fontSize: 14, borderWidth: 1, borderColor: "#D6DDCF", borderRadius: 15, backgroundColor: "#FFFFFF" }, renkler: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginTop: 16 }, renk: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" }, renkEtkin: { borderWidth: 3, borderColor: "#29322D" }, kaydet: { height: 48, borderRadius: 16, marginTop: 20, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 7, backgroundColor: "#FFB000" }, kaydetMetni: { color: "#080B10", fontSize: 13, fontWeight: "900" } });
